//DO NOT EDIT THIS FILE !

import { NestFactory } from '@nestjs/core';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import * as bodyParser from 'body-parser';
import * as dotenv from 'dotenv';
import { AppModule } from './app.module';
const fs = require('fs');

declare const module: any;
async function bootstrap() {
  dotenv.config({ path: `.env.local`, override: true });
  const app = await NestFactory.create(AppModule, { cors: true });
  app.use(bodyParser.json({ limit: '50mb' }));
  app.use(bodyParser.urlencoded({ limit: '50mb', extended: true }));
  app.enableCors({ origin: '*' });
  app.setGlobalPrefix('api');

  const config = new DocumentBuilder()
    .setTitle('mental heath')
    .setDescription('Một dự án phát triển bởi những developers đẳng cấp')
    .setVersion('1.0')
    .addTag('mental heath')
    .addBearerAuth(
      {
        description: `[just text field] Please enter token in following format: Bearer <JWT>`,
        name: 'Authorization',
        bearerFormat: 'Bearer',
        scheme: 'Bearer',
        type: 'http',
        in: 'Header',
      },
      'Authorization',
    )
    .build();
  const document = SwaggerModule.createDocument(app, config);
  fs.writeFileSync('./swagger-spec.json', JSON.stringify(document));

  SwaggerModule.setup('api', app, document);
  await app.listen(3003);

  if (module.hot) {
    module.hot.accept();
    module.hot.dispose(() => app.close());
  }
  console.log('status server: ', process.env.NODE_ENV);
}
bootstrap();
